version: '3.8'
services:
  dev-nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@dev-db:5432/${DB_NAME}?schema=public
    ports:
      - 80:3000
    depends_on:
      - dev-db
    command: sh -c "yarn prisma:migrate && yarn prisma:seed && yarn start:prod"

  dev-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
